# Generated by Django 5.2.7 on 2025-10-23 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='题目代码')),
                ('qpage', models.IntegerField(default=1, verbose_name='试卷页码')),
                ('apage', models.IntegerField(default=1, verbose_name='答案页码')),
                ('spage', models.IntegerField(default=1, verbose_name='大纲页码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='键')),
                ('value', models.TextField(verbose_name='值')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='学科代码')),
                ('name', models.CharField(max_length=255, verbose_name='学科名称')),
                ('exam_code', models.CharField(max_length=10, verbose_name='考试代码')),
                ('syllabus_url', models.URLField(blank=True, verbose_name='大纲URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='pastpaper.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '浏览历史',
                'verbose_name_plural': '浏览历史',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pastpaper.subject', verbose_name='所属学科'),
        ),
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='试卷代码')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('session', models.CharField(max_length=10, verbose_name='考试季')),
                ('paper_num', models.CharField(max_length=10, verbose_name='试卷编号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='pastpaper.subject', verbose_name='所属学科')),
            ],
            options={
                'verbose_name': '历年试卷',
                'verbose_name_plural': '历年试卷',
                'ordering': ['-year', 'session', 'paper_num'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_num', models.IntegerField(verbose_name='单元编号')),
                ('name', models.CharField(max_length=255, verbose_name='单元名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='pastpaper.subject', verbose_name='所属学科')),
            ],
            options={
                'verbose_name': '单元',
                'verbose_name_plural': '单元',
                'ordering': ['subject', 'unit_num'],
                'unique_together': {('subject', 'unit_num')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pastpaper.unit', verbose_name='所属单元'),
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill', models.BooleanField(default=False, verbose_name='已完成')),
                ('save', models.BooleanField(default=False, verbose_name='已保存')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='pastpaper.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户标签',
                'verbose_name_plural': '用户标签',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
