# Generated by Django 5.2.7 on 2025-11-10 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastpaper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaperTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill', models.BooleanField(default=False, verbose_name='已完成')),
                ('saved', models.BooleanField(default=False, db_column='pp_save', verbose_name='已保存')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('past_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='pastpaper.pastpaper', verbose_name='历年试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastpaper_tags', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '历年试卷标签',
                'verbose_name_plural': '历年试卷标签',
                'unique_together': {('user', 'past_paper')},
            },
        ),
    ]
