# Generated by Django 5.2.7 on 2025-11-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastpaper', '0002_add_pastpaper_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='save',
            field=models.BooleanField(db_column='save', default=False, verbose_name='已保存'),
        ),
        migrations.RenameField(
            model_name='usertag',
            old_name='save',
            new_name='saved',
        ),
    ]
