# Generated by Django 5.2.7 on 2025-12-02 10:40

from django.db import migrations, models


def normalize_syllabus_filenames(apps, schema_editor):
    Subject = apps.get_model('pastpaper', 'Subject')
    prefixes = ('media/', '/media/', 'media\\', '\\media\\')
    for subject in Subject.objects.exclude(syllabus_url=''):
        raw_value = (subject.syllabus_url or '').strip()
        if not raw_value:
            continue
        normalized = raw_value.replace('\\', '/')
        lower_value = normalized.lower()
        if lower_value.startswith('http://') or lower_value.startswith('https://'):
            normalized = normalized.split('://', 1)[1]
        for prefix in prefixes:
            if normalized.startswith(prefix):
                normalized = normalized[len(prefix):]
        normalized = normalized.lstrip('/')
        if subject.syllabus_url != normalized:
            subject.syllabus_url = normalized
            subject.save(update_fields=['syllabus_url'])


class Migration(migrations.Migration):

    dependencies = [
        ('pastpaper', '0004_unit_syllabus_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='syllabus_url',
            field=models.CharField(
                blank=True,
                help_text='请填写media目录下的文件名，例如 9618-2021-2023-syllabus.pdf',
                max_length=255,
                verbose_name='大纲文件名',
            ),
        ),
        migrations.RunPython(normalize_syllabus_filenames, migrations.RunPython.noop),
    ]
